[package]
name = "nym-credential-client-wasm"
authors = []
version = "1.2.0-rc.9"
edition = "2021"
keywords = ["nym", "sphinx", "wasm", "webassembly", "privacy", "client"]
license = "Apache-2.0"
repository = "https://github.com/nymtech/nym"
description = "A webassembly client which can be used to issue Coconut credentials."
rust-version = "1.56"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
futures = { workspace = true }
js-sys = { workspace = true }
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
thiserror =  { workspace = true }
tsify = { workspace = true, features = ["js"] }

wasm-client-core = { path = "../../common/wasm/client-core" }
wasm-utils = { path = "../../common/wasm/utils" }

nym-credentials = { path = "../../common/credentials" }
nym-bandwidth-controller = { path = "../../common/bandwidth-controller" }
nym-validator-client = { path = "../../common/client-libs/validator-client", features = ["http-client"] }
nym-crypto = { path = "../../common/crypto" }
nym-coconut-interface = { path = "../../common/coconut-interface" }
nym-network-defaults = { path = "../../common/network-defaults" }

[dev-dependencies]
wasm-bindgen-test = "0.3.36"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
